import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { getConfig } from '../../config/index.js';
import { getSPAPIClient } from '../../client/sp-api-client.js';
import { downloadReportDocument } from '../../utils/report-poller.js';
import { parseCSV } from '../../utils/csv-parser.js';
import { REPORT_TYPES } from '../../types/sp-api.js';
import type { GetReportsResponse, Report } from '../../types/sp-api.js';

// Input schema
const getSettlementReportSchema = z.object({
  startDate: z.string().describe('Start date in YYYY-MM-DD format'),
  endDate: z.string().describe('End date in YYYY-MM-DD format'),
});

// Settlement record type (flat file format)
interface SettlementRecord {
  settlement_id: string;
  settlement_start_date: string;
  settlement_end_date: string;
  deposit_date: string;
  total_amount: string;
  currency: string;
  transaction_type: string;
  order_id: string;
  merchant_order_id: string;
  adjustment_id: string;
  shipment_id: string;
  marketplace_name: string;
  amount_type: string;
  amount_description: string;
  amount: string;
  fulfillment_id: string;
  posted_date: string;
  posted_date_time: string;
  order_item_code: string;
  merchant_order_item_id: string;
  merchant_adjustment_item_id: string;
  sku: string;
  quantity_purchased: string;
  promotion_id: string;
}

// Group settlement rows by a key, summing the `amount` column. Shared by the transaction-type and
// amount-type breakdowns so the aggregation logic lives in one place.
function groupByAmount(
  records: SettlementRecord[],
  keyOf: (r: SettlementRecord) => string
): Record<string, { count: number; amount: number }> {
  return records.reduce(
    (acc, r) => {
      const type = keyOf(r) || 'Other';
      if (!acc[type]) {
        acc[type] = { count: 0, amount: 0 };
      }
      acc[type].count++;
      acc[type].amount += parseFloat(r.amount) || 0;
      return acc;
    },
    {} as Record<string, { count: number; amount: number }>
  );
}

export function registerSettlementTools(server: McpServer): void {
  server.registerTool(
    'get_settlement_report',
    {
      description:
        'Get settlement reports showing payment disbursements (order sales, refunds, fees, other charges). Settlement reports are auto-generated by Amazon on its own disbursement schedule and CANNOT be requested on demand, so this lists the already-generated settlement reports created within the date range and aggregates them.',
      inputSchema: getSettlementReportSchema,
    },
    async (input) => {
      const config = getConfig();
      const client = getSPAPIClient();

      // Settlement reports are auto-generated on Amazon's schedule; createReport is rejected for
      // them ("Request for report type ... not allowed at this time"). Instead, LIST the already-
      // generated DONE settlement reports created within the requested window, then download them.
      // Page through nextToken so a wide window is not silently truncated at the first 100 reports.
      const available: Report[] = [];
      let nextToken: string | undefined;
      let page = 0;
      const maxPages = 20; // safety bound (20 x 100 = 2000 reports)

      do {
        const listResp = await client.get<GetReportsResponse>(
          '/reports/2021-06-30/reports',
          // When paging, SP-API requires nextToken to be the ONLY query parameter.
          nextToken
            ? { nextToken }
            : {
                reportTypes: [
                  REPORT_TYPES.SETTLEMENT_FLAT_FILE_V2,
                  REPORT_TYPES.SETTLEMENT_FLAT_FILE,
                ].join(','),
                processingStatuses: 'DONE',
                marketplaceIds: config.MARKETPLACE_ID,
                createdSince: `${input.startDate}T00:00:00Z`,
                createdUntil: `${input.endDate}T23:59:59Z`,
                pageSize: 100,
              },
          { rateLimitCategory: 'getReports' }
        );

        for (const r of listResp.reports || []) {
          if (r.processingStatus === 'DONE' && r.reportDocumentId) {
            available.push(r);
          }
        }
        nextToken = listResp.nextToken;
        page++;
      } while (nextToken && page < maxPages);

      if (available.length === 0) {
        const result = {
          summary: {
            dateRange: { start: input.startDate, end: input.endDate },
            settlementReportsFound: 0,
          },
          note:
            "No settlement reports were generated by Amazon in this window. Settlement reports are produced on Amazon's disbursement schedule (typically every ~2 weeks) and cannot be requested on demand. Try a wider date range, or check back after the next settlement. For granular fee/charge data in the meantime, use get_financial_events.",
        };
        return {
          content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
          structuredContent: result,
        };
      }

      // Download + parse each available settlement report and aggregate across them.
      const records: SettlementRecord[] = [];
      const reportsMeta: Array<{ reportId: string; period?: string }> = [];
      const failedReports: Array<{ reportId: string; error: string }> = [];
      // Amazon may expose both the V2 and non-V2 flat file for the same settlement; dedup by a
      // composite transaction key so individual transaction rows are retained while duplicates
      // across report versions are removed.
      const seenTransactions = new Set<string>();

      function transactionKey(rec: SettlementRecord): string {
        return [
          rec.settlement_id,
          rec.order_id,
          rec.shipment_id,
          rec.amount_type,
          rec.amount,
          rec.posted_date_time,
        ].join('|');
      }

      for (const r of available) {
        let parsed: SettlementRecord[];
        try {
          const data = await downloadReportDocument(r.reportDocumentId as string);
          parsed = parseCSV<SettlementRecord>(data, { delimiter: '\t' });
        } catch (err) {
          // Record the failure and keep going so one flaky download does not discard the rest;
          // the failure is surfaced in the response (and the totals flagged) rather than hidden.
          failedReports.push({
            reportId: r.reportId,
            error: err instanceof Error ? err.message : String(err),
          });
          continue;
        }

        const fresh = parsed.filter((rec) => !seenTransactions.has(transactionKey(rec)));
        for (const rec of fresh) {
          seenTransactions.add(transactionKey(rec));
        }
        records.push(...fresh);
        reportsMeta.push({
          reportId: r.reportId,
          period:
            r.dataStartTime && r.dataEndTime
              ? `${r.dataStartTime} -> ${r.dataEndTime}`
              : undefined,
        });
      }

      const byTransactionType = groupByAmount(records, (r) => r.transaction_type);
      const byAmountType = groupByAmount(records, (r) => r.amount_type);

      // Calculate totals
      const totalPositive = records
        .filter((r) => parseFloat(r.amount) > 0)
        .reduce((sum, r) => sum + parseFloat(r.amount), 0);

      const totalNegative = records
        .filter((r) => parseFloat(r.amount) < 0)
        .reduce((sum, r) => sum + parseFloat(r.amount), 0);

      const netAmount = totalPositive + totalNegative;
      const currency = records.find((r) => r.currency)?.currency || 'USD';

      // Get unique settlement IDs
      const settlementIds = [...new Set(records.map((r) => r.settlement_id).filter(Boolean))];

      const result = {
        summary: {
          dateRange: { start: input.startDate, end: input.endDate },
          settlementReportsFound: available.length,
          settlementCount: settlementIds.length,
          totalTransactions: records.length,
          currency,
          totalCredits: totalPositive.toFixed(2),
          totalDebits: totalNegative.toFixed(2),
          netAmount: netAmount.toFixed(2),
          ...(failedReports.length > 0 && {
            incomplete: true,
            failedReportCount: failedReports.length,
          }),
        },
        reports: reportsMeta,
        ...(failedReports.length > 0 && {
          failedReports,
          warning:
            'One or more settlement reports failed to download; the totals above exclude them and are incomplete. Retry to pick up the missing reports.',
        }),
        byTransactionType: Object.entries(byTransactionType)
          .map(([type, data]) => ({
            type,
            count: data.count,
            amount: data.amount.toFixed(2),
          }))
          .sort((a, b) => parseFloat(b.amount) - parseFloat(a.amount)),
        byAmountType: Object.entries(byAmountType)
          .map(([type, data]) => ({
            type,
            count: data.count,
            amount: data.amount.toFixed(2),
          }))
          .sort((a, b) => parseFloat(b.amount) - parseFloat(a.amount)),
        settlementIds,
        recentTransactions: records.slice(0, 50).map((r) => ({
          settlementId: r.settlement_id,
          postedDate: r.posted_date,
          transactionType: r.transaction_type,
          amountType: r.amount_type,
          amountDescription: r.amount_description,
          amount: r.amount,
          orderId: r.order_id,
          sku: r.sku,
        })),
      };

      return {
        content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
        structuredContent: result,
      };
    }
  );
}
